### PR TITLE
Fix crash where command duration is not reset when client is blocked …

### LINKED ISSUE #563: [CRASH] Command duration is not reset when client is blocked on XGROUPREAD and the stream's slot is migrated, failing an assertion
In #11012, we changed the way command durations were computed to handle the same command being executed multiple times. In #11970, we added an assert if the duration is not properly reset, potentially indicating that a call to report statistics was missed.

I found an edge case where this happens - easily reproduced by blocking a client on XGROUPREAD and migrating the stream's slot. This causes the engine to process the XGROUPREAD command twice:

1. First time, we are blocked on the stream, so we wait for unblock to come back to it a second time. In most cases, when we come back to process the command second time after unblock, we process the command normally, which includes recording the duration and then resetting it.
2. After unblocking we come back to process the command, and this is where we hit the edge case - at this point, we had already migrated the slot to another node, so we return a MOVED response. But when we do that, we don’t reset the duration field.

```
=== VALKEY BUG REPORT START: Cut & paste starting from here ===
13788:M 28 May 2024 07:34:12.289 # === ASSERTION FAILED ===
13788:M 28 May 2024 07:34:12.289 # ==> networking.c:2092 'c->duration == 0' is not true

------ STACK TRACE ------

13794 bio_lazy_free
/lib64/libpthread.so.0(pthread_cond_wait+0x1f7)[0x7f36c3010377]
src/valkey-server 127.0.0.1:21148 [cluster](bioProcessBackgroundJobs+0x138)[0x4e6d78]
/lib64/libpthread.so.0(+0x744b)[0x7f36c300a44b]
/lib64/libc.so.6(clone+0x3f)[0x7f36c2d4552f]

13793 bio_aof
/lib64/libpthread.so.0(pthread_cond_wait+0x1f7)[0x7f36c3010377]
src/valkey-server 127.0.0.1:21148 [cluster](bioProcessBackgroundJobs+0x138)[0x4e6d78]
/lib64/libpthread.so.0(+0x744b)[0x7f36c300a44b]
/lib64/libc.so.6(clone+0x3f)[0x7f36c2d4552f]

13792 bio_close_file
/lib64/libpthread.so.0(pthread_cond_wait+0x1f7)[0x7f36c3010377]
src/valkey-server 127.0.0.1:21148 [cluster](bioProcessBackgroundJobs+0x138)[0x4e6d78]
/lib64/libpthread.so.0(+0x744b)[0x7f36c300a44b]
/lib64/libc.so.6(clone+0x3f)[0x7f36c2d4552f]

13788 valkey-server *
src/valkey-server 127.0.0.1:21148 [cluster][0x467287]
src/valkey-server 127.0.0.1:21148 [cluster][0x552443]
src/valkey-server 127.0.0.1:21148 [cluster][0x52f049]
src/valkey-server 127.0.0.1:21148 [cluster](processCommand+0x728)[0x51d4f8]
src/valkey-server 127.0.0.1:21148 [cluster](processInputBuffer+0xd8)[0x46c4f8]
src/valkey-server 127.0.0.1:21148 [cluster](readQueryFromClient+0x46e)[0x46cb0e]
src/valkey-server 127.0.0.1:21148 [cluster][0x52043f]
src/valkey-server 127.0.0.1:21148 [cluster](aeProcessEvents+0x321)[0x4567c1]
src/valkey-server 127.0.0.1:21148 [cluster](aeMain+0x20)[0x456b50]
src/valkey-server 127.0.0.1:21148 [cluster](main+0x375)[0x451605]
/lib64/libc.so.6(__libc_start_main+0xea)[0x7f36c2c7713a]
src/valkey-server 127.0.0.1:21148 [cluster](_start+0x2a)[0x451c2a]

4/4 expected stacktraces.

------ STACK TRACE DONE ------

------ INFO OUTPUT ------
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:255.255.255
redis_git_sha1:8e3c8fd4
redis_git_dirty:1
redis_build_id:acae0fb9c5af6b19
server_mode:cluster
os:Linux 5.10.216-182.855.amzn2int.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:7.3.1
process_id:13788
process_supervised:no
run_id:e67754454b51ac45e95400802fb1d8fc47236b50
tcp_port:21148
server_time_usec:1716881652289835
uptime_in_seconds:11
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:5605620
executable:/local/workplace/caronita/valkey/src/valkey-server
config_file:/local/workplace/caronita/valkey/./tests/tmp/valkey.conf.10352.76
io_threads_active:0
listener0:name=tcp,bind=127.0.0.1,port=21148
listener1:name=unix,bind=/local/workplace/caronita/valkey/tests/tmp/server.10352.75/socket

# Clients
connected_clients:2
cluster_connections:10
maxclients:10000
client_recent_max_input_buffer:20607
client_recent_max_output_buffer:20504
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0

# Memory
used_memory:2696056
used_memory_human:2.57M
used_memory_rss:8060928
used_memory_rss_human:7.69M
used_memory_peak:2696056
used_memory_peak_human:2.57M
used_memory_peak_perc:100.06%
used_memory_overhead:2308387
used_memory_startup:2232056
used_memory_dataset:387669
used_memory_dataset_perc:83.55%
allocator_allocated:2712520
allocator_active:3026944
allocator_resident:9936896
allocator_muzzy:0
total_system_memory:65872703488
total_system_memory_human:61.35G
used_memory_lua:31744
used_memory_vm_eval:31744
used_memory_lua_human:31.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:33792
used_memory_vm_total:65536
used_memory_vm_total_human:64.00K
used_memory_functions:184
used_memory_scripts:184
used_memory_scripts_human:184B
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.12
allocator_frag_bytes:314424
allocator_rss_ratio:3.28
allocator_rss_bytes:6909952
rss_overhead_ratio:0.81
rss_overhead_bytes:-1875968
mem_fragmentation_ratio:3.08
mem_fragmentation_bytes:5440480
mem_not_counted_for_evict:0
mem_replication_backlog:20508
mem_total_replication_buffers:20504
mem_clients_slaves:0
mem_clients_normal:44919
mem_cluster_links:10720
mem_aof_buffer:0
mem_allocator:jemalloc-5.3.0
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:3
rdb_bgsave_in_progress:0
rdb_last_save_time:1716881641
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:385024
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:4
total_commands_processed:241
instantaneous_ops_per_sec:12
total_net_input_bytes:7479
total_net_output_bytes:278295
total_net_repl_input_bytes:0
total_net_repl_output_bytes:511
instantaneous_input_kbps:0.46
instantaneous_output_kbps:12.76
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.06
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:1
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:3
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:314
total_forks:1
migrate_cached_sockets:1
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:1
dump_payload_sanitizations:0
total_reads_processed:242
total_writes_processed:229
io_threaded_reads_processed:0
io_threaded_writes_processed:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:3
reply_buffer_expands:0
eventloop_cycles:1511
eventloop_duration_sum:120095
eventloop_duration_cmd_sum:10361
instantaneous_eventloop_cycles_per_sec:147
instantaneous_eventloop_duration_usec:33
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0

# Replication
role:master
connected_slaves:1
slave0:ip=127.0.0.1,port=21145,state=online,offset=209,lag=0
master_failover_state:no-failover
master_replid:370ddacd97b1accd995eaadfb434be53b2115b49
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:268
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:268

# CPU
used_cpu_sys:0.028594
used_cpu_user:0.057189
used_cpu_sys_children:0.000000
used_cpu_user_children:0.001001
used_cpu_sys_main_thread:0.028416
used_cpu_user_main_thread:0.056832

# Modules

# Commandstats
cmdstat_migrate:calls=1,usec=250,usec_per_call=250.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|setslot:calls=2,usec=28,usec_per_call=14.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|info:calls=1,usec=46,usec_per_call=46.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|nodes:calls=1,usec=80,usec_per_call=80.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|meet:calls=5,usec=69,usec_per_call=13.80,rejected_calls=0,failed_calls=0
cmdstat_cluster|shards:calls=199,usec=8825,usec_per_call=44.35,rejected_calls=0,failed_calls=0
cmdstat_cluster|addslotsrange:calls=1,usec=106,usec_per_call=106.00,rejected_calls=0,failed_calls=0
cmdstat_cluster|slots:calls=10,usec=317,usec_per_call=31.70,rejected_calls=0,failed_calls=0
cmdstat_cluster|myid:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=2,usec=2,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_xreadgroup:calls=0,usec=0,usec_per_call=0.00,rejected_calls=1,failed_calls=0
cmdstat_replconf:calls=15,usec=161,usec_per_call=10.73,rejected_calls=0,failed_calls=0
cmdstat_psync:calls=1,usec=426,usec_per_call=426.00,rejected_calls=0,failed_calls=0
cmdstat_xgroup|create:calls=1,usec=31,usec_per_call=31.00,rejected_calls=0,failed_calls=0
cmdstat_config|get:calls=1,usec=10,usec_per_call=10.00,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_ASK:count=1

# Latencystats
latency_percentiles_usec_migrate:p50=250.879,p99=250.879,p99.9=250.879
latency_percentiles_usec_cluster|setslot:p50=7.007,p99=21.119,p99.9=21.119
latency_percentiles_usec_cluster|info:p50=46.079,p99=46.079,p99.9=46.079
latency_percentiles_usec_cluster|nodes:p50=80.383,p99=80.383,p99.9=80.383
latency_percentiles_usec_cluster|meet:p50=10.047,p99=29.055,p99.9=29.055
latency_percentiles_usec_cluster|shards:p50=44.031,p99=65.023,p99.9=72.191
latency_percentiles_usec_cluster|addslotsrange:p50=106.495,p99=106.495,p99.9=106.495
latency_percentiles_usec_cluster|slots:p50=31.103,p99=47.103,p99.9=47.103
latency_percentiles_usec_cluster|myid:p50=1.003,p99=1.003,p99.9=1.003
latency_percentiles_usec_ping:p50=1.003,p99=1.003,p99.9=1.003
latency_percentiles_usec_replconf:p50=1.003,p99=144.383,p99.9=144.383
latency_percentiles_usec_psync:p50=428.031,p99=428.031,p99.9=428.031
latency_percentiles_usec_xgroup|create:p50=31.103,p99=31.103,p99.9=31.103
latency_percentiles_usec_config|get:p50=10.047,p99=10.047,p99.9=10.047

# Cluster
cluster_enabled:1

# Keyspace

# Cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:5
cluster_my_epoch:1
cluster_stats_messages_ping_sent:417
cluster_stats_messages_pong_sent:408
cluster_stats_messages_meet_sent:5
cluster_stats_messages_sent:830
cluster_stats_messages_ping_received:408
cluster_stats_messages_pong_received:425
cluster_stats_messages_received:833
total_cluster_links_buffer_limit_exceeded:0

------ CLUSTER NODES OUTPUT ------
aa041b3e6b9a353924d0b835de8c26adcf2831eb 127.0.0.1:21146@31146,,tls-port=0,shard-id=de8469270f8cce919fed047118f77390f36d9d93 master - 0 1716881652201 0 connected 10923-16383
66508f3d9c231c1e576a2b4ecd2816d528480128 127.0.0.1:21147@31147,,tls-port=0,shard-id=ce3d6d295f0eadcebde81be7e1580fbe029b05d0 master - 0 1716881652201 3 connected 5462-10922
4b7e9dce4c5397c9256a340d0b8f922843238030 127.0.0.1:21148@31148,,tls-port=0,shard-id=7de919c9140f9168fd9ff32199d3b169b9e0e613 myself,master - 0 0 1 connected 0-5461 [609->-66508f3d9c231c1e576a2b4ecd2816d528480128]
1e33775fc8c3815341f525cbf8db4b3c5a16a18b 127.0.0.1:21145@31145,,tls-port=0,shard-id=7de919c9140f9168fd9ff32199d3b169b9e0e613 slave 4b7e9dce4c5397c9256a340d0b8f922843238030 0 1716881652201 1 connected
4eec7f352e00a438c06e223de89059211cfe57ec 127.0.0.1:21144@31144,,tls-port=0,shard-id=ce3d6d295f0eadcebde81be7e1580fbe029b05d0 slave 66508f3d9c231c1e576a2b4ecd2816d528480128 0 1716881652201 3 connected
374b2ea7996d67cb90d45ad6d3433c17d079e263 127.0.0.1:21143@31143,,tls-port=0,shard-id=de8469270f8cce919fed047118f77390f36d9d93 slave aa041b3e6b9a353924d0b835de8c26adcf2831eb 0 1716881652201 0 connected

------ CLIENT LIST OUTPUT ------
id=4 addr=127.0.0.1:48398 laddr=127.0.0.1:21148 fd=12 name= age=11 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=69 qbuf-free=20405 argv-mem=6 multi-mem=0 rbs=1024 rbp=796 obl=5 oll=0 omem=0 tot-mem=22422 events=r cmd=migrate user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6728 tot-net-out=277760 tot-cmds=223
id=5 addr=127.0.0.1:48410 laddr=127.0.0.1:21148 fd=27 name= age=11 idle=0 flags=S db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=20504 tot-mem=42904 events=r cmd=replconf user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=638 tot-net-out=263 tot-cmds=17
id=6 addr=127.0.0.1:38472 laddr=127.0.0.1:21148 fd=28 name= age=1 idle=1 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=26 obl=26 oll=0 omem=0 tot-mem=22400 events=r cmd=xreadgroup user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=106 tot-net-out=0 tot-cmds=0

------ CURRENT CLIENT INFO ------
id=6 addr=127.0.0.1:38472 laddr=127.0.0.1:21148 fd=28 name= age=1 idle=1 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=26 obl=26 oll=0 omem=0 tot-mem=22400 events=r cmd=xreadgroup user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=106 tot-net-out=0 tot-cmds=0
argc: '0'

------ MODULES INFO OUTPUT ------

------ CONFIG DEBUG OUTPUT ------
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
client-query-buffer-limit 1gb
activedefrag no
list-compress-depth 0
lazyfree-lazy-eviction no
slave-read-only yes
lazyfree-lazy-user-del no
lazyfree-lazy-user-flush no
io-threads 1
replica-read-only yes
sanitize-dump-payload no
repl-diskless-load disabled
repl-diskless-sync yes
io-threads-do-reads no
proto-max-bulk-len 512mb

------ FAST MEMORY TEST ------
13788:M 28 May 2024 07:34:12.294 # Bio worker thread #0 terminated
13788:M 28 May 2024 07:34:12.294 # Bio worker thread #1 terminated
13788:M 28 May 2024 07:34:12.294 # Bio worker thread #2 terminated
*** Preparing to test memory region 8f9000 (2306048 bytes)
*** Preparing to test memory region 13a4000 (135168 bytes)
*** Preparing to test memory region 7f36b85fd000 (10485760 bytes)
*** Preparing to test memory region 7f36b8ffe000 (10485760 bytes)
*** Preparing to test memory region 7f36b99ff000 (10485760 bytes)
*** Preparing to test memory region 7f36ba400000 (10485760 bytes)
*** Preparing to test memory region 7f36bae00000 (6291456 bytes)
*** Preparing to test memory region 7f36bb5b1000 (2621440 bytes)
*** Preparing to test memory region 7f36c2400000 (8388608 bytes)
*** Preparing to test memory region 7f36c2fff000 (16384 bytes)
*** Preparing to test memory region 7f36c321d000 (16384 bytes)
*** Preparing to test memory region 7f36c3b7b000 (28672 bytes)
*** Preparing to test memory region 7f36c3b92000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== VALKEY BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           https://github.com/valkey-io/valkey/issues

  If a module was involved, please open in the module's repo instead.

  Suspect RAM error? Use valkey-server --test-memory to verify it.

  Some other issues could be detected by valkey-server --check-system
```

### PR DESCRIPTION
**Pull request by nitaicaro**
In 383d902ce68131cf40d6122ce09e305e672e8555, we changed the way command durations were computed to handle the same command being executed multiple times. In #11970, we added an assert if the duration is not properly reset, potentially indicating that a call to report statistics was missed. 

I found an edge case where this happens - easily reproduced by blocking a client on `XGROUPREAD` and migrating the stream's slot. This causes the engine to process the `XGROUPREAD` command twice:

1. First time, we are blocked on the stream, so we wait for unblock to come back to it a second time. In most cases, when we come back to process the command second time after unblock, we process the command normally, which includes recording the duration and then resetting it.
2. After unblocking we come back to process the command, and this is where we hit the edge case - at this point, we had already migrated the slot to another node, so we return a `MOVED` response. But when we do that, we don’t reset the duration field.

Fix: also reset the duration when returning a `MOVED` response. I think this is right, because the client should redirect the command to the right node, which in turn will calculate the execution duration.

Also wrote a test which reproduces this, it fails without the fix and passes with it.

Fixes #563

### CODE REVIEW

File: src/server.c [hunk 1]
```diff
@@ -4034,6 +4034,7 @@ int processCommand(client *c) {
                 flagTransaction(c);
             }
             clusterRedirectClient(c,n,c->slot,error_code);
+            c->duration = 0;
```
Comment (ranshid) [inline src/server.c:3886]: why not place this in clusterRedirectClient?

File: tests/cluster/cluster.tcl [hunk 2]
```diff
@@ -59,6 +59,30 @@ proc get_node_by_id {instance_id node_id} {
     return {}
 }
 
+# Get info on the node that owns a specific slot by parsing
+# the CLUSTER NODES output of the instance Number 'instance_id'
+proc get_slot_owner_info {instance_id slot} {
```
Comment (ranshid) [inline tests/cluster/cluster.tcl]: 1. I think you can make this utility function just get the node index to the node you are questioning (like 0 for R0 and 1 for R1)
2. I would try and avoid reading the data from slaves (just optimization)

File: tests/cluster/tests/10-slot-migration-with-client-blocking.tcl [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+test "Cluster is up" {
+    assert_cluster_state ok
+}
+
+set cluster [valkey_cluster 127.0.0.1:[get_instance_attrib valkey 0 port]]
+
+test "Initialize stream and blocked client" {
+    $cluster xgroup create stream mygroup $ MKSTREAM
+    # stream maps to 1386
+    set slot 1386
```
Comment (ranshid) [inline tests/cluster/tests/10-slot-migration-with-client-blocking.tcl]: can we just call CLUSTER KEYSLOT to get the slot?

File: tests/cluster/tests/10-slot-migration-with-client-blocking.tcl [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+    create_cluster 3 0
+}
+
+test "Cluster is up" {
+    assert_cluster_state ok
+}
+
+set cluster [valkey_cluster 127.0.0.1:[get_instance_attrib valkey 0 port]]
+
+test "Initialize stream and blocked client" {
```
Comment (ranshid) [inline tests/cluster/tests/10-slot-migration-with-client-blocking.tcl]: Not sure why this test is needed?
You can't separate initialization from another test since each test can be run separately.

File: tests/cluster/tests/10-slot-migration-with-client-blocking.tcl [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+    $cluster xgroup create stream mygroup $ MKSTREAM
+    # stream maps to 1386
+    set slot 1386
+    # Start a background process to simulate a blocked client on XREADGROUP
+    set clientpid [exec sh -c "echo 'xreadgroup GROUP mygroup consumer BLOCK 0 streams stream >' | ../../../src/valkey-cli -c -p [get_instance_attrib valkey 0 port]" &]
+    after 1000
+}
+
+test "Regression test for a crash where a node is blocked on XREADGROUP and the stream's slot is migrated" {
```
Comment (ranshid) [inline tests/cluster/tests/10-slot-migration-with-client-blocking.tcl]: no need to point "Regression test for a crash where a". just call it:
"test client blocked on XREADGROUP while stream's slot is migrated

File: tests/cluster/cluster.tcl (hunk 2 above)
Comment (nitaicaro) [reply tests/cluster/cluster.tcl]: It's a bit problematic as the index is not found in the info

**Review by ranshid — APPROVED** [review]
LGTM - however you need to signoff some commits

File: tests/support/cluster_util.tcl [hunk 6]
```diff
@@ -305,6 +305,41 @@ proc get_cluster_nodes {id {status "*"}} {
...
+                set max [expr {$max}]
+                if {$slot >= $min && $slot <= $max} {
+                    return $n
+                }
+            } else {
+                fail "Unexpected format in CLUSTER NODES"
+            }
+        }
+    }
+}
```
Comment (PingXie) [inline tests/support/cluster_util.tcl]: fail the call if the slot is not found?

File: tests/support/cluster_util.tcl [hunk 7]
```diff
@@ -305,6 +305,41 @@ proc get_cluster_nodes {id {status "*"}} {
     return $nodes
 }
 
+# Get info on the node that owns a specific slot by parsing
+# the CLUSTER NODES output of the instance Number 'instance_id'
+proc get_slot_owner_info {slot {instance_id 0}} {
+    set nodes [get_cluster_nodes $instance_id]
+    foreach n $nodes {
+        set slots [dict get $n slots]
+        foreach _slot $slots {
```
Comment (PingXie) [inline tests/support/cluster_util.tcl]: nit. `_slot` seems a bit unconventional. I don't remember seeing it in the tests before. how about `current_slot` or `s`?

```suggestion
        foreach s $slots {
```

File: tests/unit/cluster/slot-migration.tcl [hunk 8]
```diff
@@ -355,3 +355,30 @@ start_cluster 3 3 {tags {external:skip cluster} overrides {crash-memcheck-enable
...
+        # Start a background process to simulate a blocked client on XREADGROUP
+        R $source XGROUP CREATE $stream_name mygroup $ MKSTREAM
+        exec sh -c "echo 'xreadgroup GROUP mygroup consumer BLOCK 0 streams $stream_name >' | src/valkey-cli -h 127.0.0.1 -p [lindex [R $source CONFIG GET port] 1] " &
+        after 1000
+
+        # Migrate the slot to the target node
+        R $source CLUSTER SETSLOT $slot MIGRATING $target_cluster_id
+        R $target CLUSTER SETSLOT $slot IMPORTING $source_cluster_id
+
+        # This line should cause the crash
```
Comment (PingXie) [inline tests/unit/cluster/slot-migration.tcl:442]: I'd suggest capturing the context of the bug here in the comment, something like unblocking the xgroupread client by migrating the stream away to a different node and this should cause the client duration to be reset properly, avoiding an assert/crash. Or you could just link the bug in the comment (seems to be a common practice). 

```suggestion
        # This line should cause the crash
```

File: tests/support/cluster_util.tcl [hunk 9]
```diff
@@ -305,6 +305,41 @@ proc get_cluster_nodes {id {status "*"}} {
...
+    set i 0
+    while {1} {
+        set my_info [cluster_get_myself $i]
+        if {[dict get $my_info id] == $id} {
+            return $i
+        }
+        incr i 
+    }
+}
+
```
Comment (PingXie) [inline tests/support/cluster_util.tcl]: Will this lead to an infinite loop if $id is non-existent?

File: tests/unit/cluster/slot-migration.tcl [hunk 10]
```diff
@@ -355,3 +355,30 @@ start_cluster 3 3 {tags {external:skip cluster} overrides {crash-memcheck-enable
         assert_equal {NOREPLICAS Not enough good replicas to write.} $e
     }
 }
+
+start_cluster 3 3 {tags {external:skip cluster regression} overrides {cluster-allow-replica-migration no cluster-node-timeout 1000} } {
+    test "Client blocked on XREADGROUP while stream's slot is migrated" {
+        set stream_name stream
```
Comment (PingXie) [inline tests/unit/cluster/slot-migration.tcl]: another option to avoid the look up is to use well-known names like `aga` which maps to slot 609. with the sequential slot allocator, slot 609 will land on R 0 and then R 1 can be used for the target.

**Review by PingXie — COMMENTED** [review]
The code change makes sense to me. I think we can merge if you could address the comments on the test code.

The assert though sounds harsh to me. I am not sure if the tradeoff (accurate metrics vs server crash) is justified but agreed it is a separate issue.

File: tests/unit/cluster/slot-migration.tcl (hunk 10 above)
Comment (nitaicaro) [reply tests/unit/cluster/slot-migration.tcl]: If this is acceptable then I think this makes more sense, and will obviate the need for the utility functions

**Comment by nitaicaro** [comment]
@PingXie, agreed that the assert is a bit harsh. When @madolson [added it originally](https://github.com/valkey-io/valkey/commit/971b177fa) she did point out that it can potentially be removed in the future. I can remove it in this PR as it's been over a year, what do you think?

**Comment by PingXie** [comment]
> @PingXie, agreed that the assert is a bit harsh. When @madolson [added it originally](https://github.com/valkey-io/valkey/commit/971b177fa) she did point out that it can potentially be removed in the future. I can remove it in this PR as it's been over a year, what do you think?

I think we should address the assert separately. If we remove that assert, this PR would become moot :-).


As for the assert, I would like to hear the community's thoughts on the following:

1. rename `assert` to `panic` - `assert` in Redis/Valkey is a misnomer.; it is actually `panic`. 
2. introduce `debug`  builds and  real `assert`s,which exist in `debug` builds only;
4. convert this assert (`c->duration == 0`) to a (real) runtime assert - there is still value in checking this condition
5. add daily test runs against both `debug` builds as well (in addition to the current "release" builds)

**Comment by ranshid** [comment]
> > @PingXie, agreed that the assert is a bit harsh. When @madolson [added it originally](https://github.com/valkey-io/valkey/commit/971b177fa) she did point out that it can potentially be removed in the future. I can remove it in this PR as it's been over a year, what do you think?
> 
> I think we should address the assert separately. If we remove that assert, this PR would become moot :-).
> 
> As for the assert, I would like to hear the community's thoughts on the following:
> 
> 1. rename `assert` to `panic` - `assert` in Redis/Valkey is a misnomer.; it is actually `panic`.

I think that it is a well known difference between assert and panic. panic means "abort now no matter what" and assert is a conditional abort like "test and abort if condition is not met"

> 2. introduce `debug`  builds and  real `assert`s,which exist in `debug` builds only;

I strongly support introducing debug_assert in valkey. I think the logic of assert/panic is to abort in case the program encounter a condition which prevents it from continue to operate correctly and/or fix. I think it will also help improve the stability and we might be more lose with adding debug_asserts which will help identify bugs during daily runs.

> 3. convert this assert (`c->duration == 0`) to a (real) runtime assert - there is still value in checking this condition

I am not 100% sure that this should not become a debug_assert. I find value in what you propose since it maybe a result of a real consistency issue (?) but I still feel the purpose here was to catch issues during tests.
 
> 4. add daily test runs against both `debug` builds as well (in addition to the current "release" builds)

Is there really a reason to run non debug daily tests? I agree performance tests should run "release" builds but maybe we can just run the daily with debug builds in order to reduce the extra resource utilization?

File: tests/unit/cluster/slot-migration.tcl (hunk 10 above)
Comment (ranshid) [reply tests/unit/cluster/slot-migration.tcl]: I wonder if the utility function will not come in handy someday? I have no strong argue to keep it, but it is only for tests...

File: tests/unit/cluster/slot-migration.tcl (hunk 8 above)
Comment (nitaicaro) [reply tests/unit/cluster/slot-migration.tcl:442]: Added comment to the test - `# Issue #563 regression test`

**Comment by PingXie** [comment]
> I think that it is a well known difference between assert and panic. panic means "abort now no matter what" and assert is a conditional abort like "test and abort if condition is not met"

I meant to say "conditional" panic, something like `serverPanicIf(cond)`. [assert](https://en.cppreference.com/w/cpp/error/assert) is not supposed to take down a running process/system.

>I strongly support introducing debug_assert in valkey. I think the logic of assert/panic is to abort in case the program encounter a condition which prevents it from continue to operate correctly and/or fix. I think it will also help improve the stability and we might be more lose with adding debug_asserts which will help identify bugs during daily runs.

I feel that we are talking about two different things. What you described here aligns with my definition of the `panic` behavior, meaning that the violation of the invariant has severe consequences such as leading to data loss if not being held. the violation of `c->duration ==0` does not fit this bill. However, there is still value in making sure that we don't just generate random metrics and this is why I think `assert` is the right tool because it is only active in the special `debug` builds that are not used in any prod env.

>I am not 100% sure that this should not become a debug_assert. I find value in what you propose since it maybe a result of a real consistency issue (?) but I still feel the purpose here was to catch issues during tests.

I agree with you (and I call `debug_assert` as `serverPanicIf`). That said, I still think we should try our best to catch this invariant violation (using `assert`)

>Is there really a reason to run non debug daily tests? I agree performance tests should run "release" builds but maybe we can just run the daily with debug builds in order to reduce the extra resource utilization?

Yes I think running the daily with `debug` builds makes sense. Performance tests can run weekly or right after any PR marked with "performance enhancement" on-demand.

**Comment by madolson** [comment]
> I meant to say "conditional" panic, something like serverPanicIf(cond). [assert](https://en.cppreference.com/w/cpp/error/assert) is not supposed to take down a running process/system.

We don't use assert that way, so I don't know if it's worth arguing about what `assert` should and shouldn't do. BTW, we don't use `assert` anywhere in Valkey, it is always replaced by serverAssert() which is always active in production.

> I can remove it in this PR as it's been over a year, what do you think?

At the time I was also advocating for the addition `debugServerAssertWithInfo` which more closely fits what we were looking for (specifically what Ping refers to with assert), but hadn't committed to at the time. It fills the role of "only assert during tests". I think we can move from a regular serverAssert to the debug variant. We should also reset the duration to zero if we aren't already, to make sure we are gracefully handling production cases.

File: tests/unit/cluster/slot-migration.tcl [hunk 11]
```diff
@@ -355,3 +355,23 @@ start_cluster 3 3 {tags {external:skip cluster} overrides {crash-memcheck-enable
...
+start_cluster 3 3 {tags {external:skip cluster regression} overrides {cluster-allow-replica-migration no cluster-node-timeout 1000} } {
+    # Issue #563 regression test
+    test "Client blocked on XREADGROUP while stream's slot is migrated" {
+        set stream_name aga
+        set slot 609
+
+        # Start a background process to simulate a blocked client on XREADGROUP
+        R 0 XGROUP CREATE $stream_name mygroup $ MKSTREAM
+        exec sh -c "echo 'xreadgroup GROUP mygroup consumer BLOCK 0 streams $stream_name >' | src/valkey-cli -h 127.0.0.1 -p [lindex [R 0 CONFIG GET port] 1] " &
+        after 1000
```
Comment (madolson) [inline tests/unit/cluster/slot-migration.tcl]: Why don't we use a deferring client for this? It seems a lot more reliable than starting up the CLI.

**Comment by PingXie** [comment]
> We don't use assert that way, so I don't know if it's worth arguing about what `assert` should and shouldn't do. BTW, we don't use `assert` anywhere in Valkey, it is always replaced by serverAssert() which is always active in production.

I understand Redis/Valkey never used "asserts" in that way, which is unconventional IMO, but I agree the debate on semantics is sufficient at this moment. What I'm trying to say is that with today's code base we either have to take down the server on non-critical invariant violation like this one or have no way to detect for ever and we can do better.

> At the time I was also advocating for the addition `debugServerAssertWithInfo` which more closely fits what we were looking for (specifically what Ping refers to with assert), but hadn't committed to at the time. It fills the role of "only assert during tests". I think we can move from a regular serverAssert to the debug variant.

"assert" that only fires during tests would totally work for me. Do you have an issue on it already? 

> We should also reset the duration to zero if we aren't already, to make sure we are gracefully handling production cases.

Agreed

**Comment by madolson** [comment]
> "assert" that only fires during tests would totally work for me. Do you have an issue on it already?

This already exists today, it's `debugServerAssertWithInfo`. By default `debugServerAssertWithInfo` is compiled out, but it's compiled in for some tests. See `-DDEBUG_ASSERTIONS` like https://github.com/valkey-io/valkey/blob/fd58b73f0ae895bf9de3810d799da20bb75a2b4f/.github/workflows/daily.yml#L601C102-L601C120.

File: src/cluster.c [hunk 12]
```diff
@@ -1237,6 +1237,7 @@ void clusterRedirectClient(client *c, clusterNode *n, int hashslot, int error_co
     } else {
         serverPanic("getNodeByQuery() unknown error.");
     }
+    c->duration = 0;
```
Comment (madolson) [inline src/cluster.c]: I'm curious why we wouldn't just put the c->duration here: https://github.com/valkey-io/valkey/blob/fd58b73f0ae895bf9de3810d799da20bb75a2b4f/src/server.c#L3886. It's more align with all the other reject calls.

File: tests/unit/cluster/slot-migration.tcl [hunk 13]
```diff
@@ -355,3 +355,23 @@ start_cluster 3 3 {tags {external:skip cluster} overrides {crash-memcheck-enable
         assert_equal {NOREPLICAS Not enough good replicas to write.} $e
     }
 }
+
+start_cluster 3 3 {tags {external:skip cluster regression} overrides {cluster-allow-replica-migration no cluster-node-timeout 1000} } {
```
Comment (madolson) [inline tests/unit/cluster/slot-migration.tcl]:
```suggestion
start_cluster 2 0 {tags {external:skip cluster regression} overrides {cluster-allow-replica-migration no cluster-node-timeout 1000} } {
```

We don't need so many nodes, this will make it faster.

File: src/cluster.c (hunk 12 above)
Comment (nitaicaro) [reply src/cluster.c]: > I'm curious why we wouldn't just put the c->duration here:
> 
> https://github.com/valkey-io/valkey/blob/fd58b73f0ae895bf9de3810d799da20bb75a2b4f/src/server.c#L3886
> 
> . It's more align with all the other reject calls.

That's where it was originally, but @ranshid pointed out that this could potentially happen in other flows that reach `clusterRedirectClient`, for example from `clusterRedirectBlockedClientIfNeeded`

Comment (ranshid) [reply src/cluster.c]: I think this better follows the fact that the duration is zeroed in rejectCommand and rejectCommandSds. clusterRedirectClient is something similar IMO.
While we are at it, why not move the c->cmd->rejected_calls++; to clusterRedirectClient? for example: are we incrementing it when we move   list blocked clients? From short glance at the code I think not.

Comment (madolson) [reply src/cluster.c]: > clusterRedirectBlockedClientIfNeeded

We reset duration during the unblock flow in this case, so it should not be needed. 

> clusterRedirectClient is something similar IMO

As it's implemented it is not though. clusterRedirectClient is a specific function for throwing errors while rejectCommand handles a bunch of state related to command rejection during process command. I'd rather modify the reject code so we *also* call some form of rejectClientByRedirect().

Comment (nitaicaro) [reply src/cluster.c]: @madolson moved it back to processCommand

Comment (ranshid) [reply src/cluster.c]: O.K I agree about changing it back mainly since adding the counter as well would indeed introduced a bug (we would have updated command failed+reject stats)
> I'd rather modify the reject code so we also call some form of rejectClientByRedirect().

 I agree that some refactor IS needed around that part. specifically I think we need to consider the blocked commands should follow the logic presented in https://github.com/valkey-io/valkey/commit/90b9f08e5d1657e7bfffe43f31f6663bf469ee75 so that in case blocked commands are also rejected the correct counter will be updated (this should be a different PR)

File: tests/unit/cluster/slot-migration.tcl [hunk 14]
```diff
@@ -422,3 +422,24 @@ start_cluster 3 3 {tags {external:skip cluster} overrides {cluster-allow-replica
...
+    # Issue #563 regression test
+    test "Client blocked on XREADGROUP while stream's slot is migrated" {
+        set stream_name aga
+        set slot 609
+
+        # Start a background process to simulate a blocked client on XREADGROUP
+        R 0 XGROUP CREATE $stream_name mygroup $ MKSTREAM
+        set rd [valkey_deferring_client]
+        $rd xreadgroup GROUP mygroup consumer BLOCK 0 streams $stream_name >
+        after 1000
```
Comment (madolson) [inline tests/unit/cluster/slot-migration.tcl]:
```suggestion
```

I don't think this is still needed. I assume it was added previously to give time for the CLI to start, but the deferring client should send the command before the normal client.

Comment (madolson) [reply tests/unit/cluster/slot-migration.tcl]: Alternatively you can replace this with: `wait_for_blocked_client` which will wait for one client to be blocked.

**Review by madolson — COMMENTED** [review]
Just a minor comment, LGTM to otherwise.

**Review by madolson — APPROVED** [review]
