### PR TITLE
Fail fast on invalid certificates at TLS config load

### LINKED ISSUE #2997: [NEW] Fail fast on invalid certificates at TLS config load
### The problem / use-case

Currently, Valkey loads TLS configuration even if certificates are expired or not yet valid. In this state:

1. Incoming client connections fail during the TLS handshake with vague errors:

```

Server: 
33725:M 30 Dec 2025 16:39:12.116 # Error accepting a client connection: error:0A000415:SSL routines::ssl/tls alert certificate expired (addr= laddr=127.0.0.1:6379)

Client: 
Could not connect to Valkey at 127.0.0.1:6379: SSL_connect failed: certificate verify failed

```

2. Server-side client certificates (used for mutual TLS in replication or cluster gossip) may also be invalid, causing replication or cluster communication to fail silently until connections are attempted:

```

Replica:
34229:S 30 Dec 2025 16:47:31.889 * Connecting to PRIMARY 127.0.0.1:6379
34229:S 30 Dec 2025 16:47:31.889 * PRIMARY <-> REPLICA sync started
34229:S 30 Dec 2025 16:47:31.889 * Non blocking connect for SYNC fired the event.
34229:S 30 Dec 2025 16:47:31.889 # Failed to read response from the server: Undefined error: 0

Primary:
34179:M 30 Dec 2025 16:47:37.946 # Error accepting a client connection: error:0A00010B:SSL routines::wrong version number (addr=127.0.0.1:58954 laddr=127.0.0.1:6379)

```

This delayed detection makes it difficult to diagnose TLS misconfigurations and can result in clusters starting “successfully” but being partially or fully unusable. Operators currently see vague runtime-only errors instead of a clear, immediate indication of certificate problems.

### Proposed solution / feature

Fail TLS configuration immediately if any loaded certificate (server certificate, server-side client certificate, or CA certificate) is expired or not yet valid. Specifically:

- Validate the `notBefore` and `notAfter` fields of all certificates when TLS contexts are created.
- If any certificate is invalid:
  - Fail TLS configuration immediately.
  - Log a clear message specifying which certificate is invalid and why.
- Apply this to all:
  - Server certificates `tls-cert-file`
  - Server-side client certificates `tls-client-cert-file`
  - CA certificate file `tls-ca-cert-file` 
  - CA certificate directory `tls-ca-cert-dir`
- Apply to both:
  - Server startup (initial TLS load)
  - Runtime reload vis CONFIG SET

**Goal:**
Treat invalid certificates as configuration errors and prevent the server from running in an unusable state.

### PR DESCRIPTION
**Pull request by yang-z-o**
Closes https://github.com/valkey-io/valkey/issues/2997

### Overview
This PR adds the certificates validation at TLS load, rejects invalid (expired/not-yet-valid) certificates:

Apply to all TLS config paths:
- Server certificates `tls-cert-file`
- Server-side client certificates `tls-client-cert-file`
- CA certificate file `tls-ca-cert-file` 
- CA certificate directory `tls-ca-cert-dir` (now eagerly loaded to be consistent with file-based CAs)

Apply to both scenarios:
- Server startup (initial TLS load)
- Runtime reload vis `CONFIG SET`

### Implementation
- Added `isCertValid` function to check if an X509 certificate is within its validity period (not expired, not future-dated)
- Added `areAllCaCertsValid` function to iterate through all loaded CA certificates and validate them
- Added `loadCaCertDir` function to eagerly load all certificates from a directory into the X509_STORE
- Modified `createSSLContext` to validate:
  - Server/client certificates immediately after loading
  - All CA certificates after loading from file/directory

#### 1. Server startup (initial TLS load)
```
tls-cert-file ./tests/tls/server-expired.crt

41522:M 31 Dec 2025 16:13:18.851 # Server TLS certificate is invalid. Aborting TLS configuration.
41522:M 31 Dec 2025 16:13:18.851 # Failed to configure TLS. Check logs for more info.


tls-client-cert-file ./tests/tls/client-expired.crt

41557:M 31 Dec 2025 16:14:43.296 # Client TLS certificate is invalid. Aborting TLS configuration.
41557:M 31 Dec 2025 16:14:43.296 # Failed to configure TLS. Check logs for more info.


tls-ca-cert-file ./tests/tls/ca-expired.crt
tls-ca-cert-dir ./tests/tls/ca-expired

41567:M 31 Dec 2025 16:15:15.635 # One or more loaded CA certificates are invalid. Aborting TLS configuration.
41567:M 31 Dec 2025 16:15:15.635 # Failed to configure TLS. Check logs for more info.
```

#### 2. Runtime reload via CONFIG SET
```
127.0.0.1:6379> config set tls-cert-file ./tests/tls/server-expired.crt
(error) ERR CONFIG SET failed (possibly related to argument 'tls-cert-file') - Unable to update TLS configuration. Check server logs.

62975:M 02 Jan 2026 20:10:43.588 # Server TLS certificate is invalid. Aborting TLS configuration.
62975:M 02 Jan 2026 20:10:43.588 # Failed applying new configuration. Possibly related to new tls-cert-file setting. Restoring previous settings.


127.0.0.1:6379> config set tls-client-cert-file ./tests/tls/client-expired.crt
(error) ERR CONFIG SET failed (possibly related to argument 'tls-client-cert-file') - Unable to update TLS configuration. Check server logs.

62975:M 02 Jan 2026 20:10:57.972 # Client TLS certificate is invalid. Aborting TLS configuration.
62975:M 02 Jan 2026 20:10:57.972 # Failed applying new configuration. Possibly related to new tls-client-cert-file setting. Restoring previous settings.


127.0.0.1:6379> config set tls-ca-cert-file ./tests/tls/ca-expired.crt
127.0.0.1:6379> config set tls-ca-cert-dir ./tests/tls/ca-expired
(error) ERR CONFIG SET failed (possibly related to argument 'tls-ca-cert-file') - Unable to update TLS configuration. Check server logs.

62975:M 02 Jan 2026 20:10:50.175 # One or more loaded CA certificates are invalid. Aborting TLS configuration.
62975:M 02 Jan 2026 20:10:50.175 # Failed applying new configuration. Possibly related to new tls-ca-cert-file setting. Restoring previous settings.
```

### CODE REVIEW

**Comment by yang-z-o** [comment]
Hello @madolson @zuiderkwast @PingXie, I briefly mentioned this PR in last week's weekly meeting. 
This PR adds TLS certificate validation at server startup and reloads. Since it introduces a behavior change, it may require core team guidance. Would really appreciate it if you could take a look and share your thoughts. Thanks! 🙏

**Comment by zuiderkwast** [comment]
Thanks for the heads up. A small behavior change doesn't necessarily need to be a major decision, if it's backward compatible and doesn't introduce any new public API (configs, commands, etc.) and doesn't break any user scenario. So what exactly is the behavior change?

Before:

* It was possible to configure expired certificates. CONFIG SET retured OK.
* The result is that clients can't connect.

After:

* Not possible to configure expired certificates. CONFIG SET returns an error.
* Clients can still connect if the old certificates are still valid. When they expire, clients can't connect.

CONFIG SET can now return an error where it previously returned OK, but that OK was silencing a severe admin error resulting in clients unable to connect.

To me, it doesn't seem like a breaking change, so I don't think it needs to be a major decision, but @valkey-io/core-team please speak up if you think otherwise.

I (or someone else) will review this PR soon.

File: src/tls.c [hunk 1]
```diff
@@ -208,6 +210,87 @@ static int tlsPasswordCallback(char *buf, int size, int rwflag, void *u) {
     return (int)pass_len;
 }
 
+/* Check a single X509 certificate validity */
+static int is_cert_valid(X509 *cert) {
```
Comment (zuiderkwast) [inline src/tls.c]: We normally use `camelCase` for function names and `snake_case` for variables.

Consider using bool and true/false for the return value.

```suggestion
static bool isCertValid(X509 *cert) {
```

File: src/tls.c [hunk 2]
```diff
@@ -208,6 +210,87 @@ static int tlsPasswordCallback(char *buf, int size, int rwflag, void *u) {
...
+    if (!not_before || !not_after) return 0;
+    if (X509_cmp_current_time(not_before) > 0 ||
+        X509_cmp_current_time(not_after) < 0) {
+        return 0;
+    }
+    return 1;
+}
+
+/* Load all certificates from a directory into the X509_STORE */
+static int load_ca_cert_dir(SSL_CTX *ctx, const char *ca_cert_dir) {
```
Comment (zuiderkwast) [inline src/tls.c]: Please describe the meaning of the return values in this comment.

File: src/tls.c [hunk 3]
```diff
@@ -208,6 +210,87 @@ static int tlsPasswordCallback(char *buf, int size, int rwflag, void *u) {
...
+            X509_free(cert);
+        }
+    }
+
+    closedir(dir);
+    return 1;
+}
+
+/* Iterate over all CA certs in the SSL_CTX and fail-fast if any are invalid */
+int check_loaded_ca_certs(SSL_CTX *ctx) {
```
Comment (zuiderkwast) [inline src/tls.c]: Describe the meaning of the return values, or maybe use a bool return type and self-explaining yes/no-question-like name, for example areAllCaCertsValid.

**Review by zuiderkwast — COMMENTED** [review]
Looks good to me in general. I have only minor comments.

We use `camelCase` for function names and `snake_case` for variables, so please follow this style in new code. (Sorry, the style is not written anywhere. We're working on it.)

**Review by zuiderkwast — APPROVED** [review]
Looks good, thank you!

@madolson do you think the behavior change poses any risk?

**Comment by PingXie** [comment]
The new behavior is better so good from my end.

Btw, @zuiderkwast once we merge #3076 copilot should be able to take care of the coding style review (and we can keep iterating on the instructions).

**Comment by zuiderkwast** [comment]
> Btw, @zuiderkwast once we merge #3076 copilot should be able to take care of the coding style review (and we can keep iterating on the instructions).

Gotcha. I approved it now. :)

File: tests/unit/tls.tcl [hunk 4]
```diff
@@ -173,5 +173,112 @@ start_server {tags {"tls"}} {
...
+            }
+
+            set cmd [list $server_path --port 0 --tls-port 16379 \
+                --tls-cert-file $server_cert --tls-key-file $server_key \
+                --tls-client-cert-file $client_cert --tls-client-key-file $client_key]
+
+            if {$ca_cert_file ne ""} { lappend cmd --tls-ca-cert-file $ca_cert_file }
+            if {$ca_cert_dir ne ""}  { lappend cmd --tls-ca-cert-dir  $ca_cert_dir }
+
+            catch {exec {*}$cmd 2>@1} err
```
Comment (zuiderkwast) [inline tests/unit/tls.tcl:361]: I guess you mean `2>&1`. (Otherwise, it would create a file with the name `@1`.)

```suggestion
            catch {exec {*}$cmd 2>&1} err
```

Did you run these tests locally?

It appears that we don't automatically run the TLS tests in the normal CI jobs that run for each PR. The TLS Reload introduced a number of failures in the Daily runs where we run tests with TLS.

Comment (yang-z-o) [reply tests/unit/tls.tcl:361]: I usually run `make` and `make test`. The `./runtest --single tests/unit/tls.tcl --tls` consistently fails for me on macOS, mostly due to OpenSSL configuration, and I haven’t found a solution yet.

Because of that, I pushed the changes to my fork to rely on CI for coverage, but I didn’t realize that the CI jobs don’t run the TLS tests either.

Comment (yang-z-o) [reply tests/unit/tls.tcl:361]: Oh I see https://github.com/valkey-io/valkey/pull/3090/files

Comment (yang-z-o) [reply tests/unit/tls.tcl:361]: `2>@1` This redirects file descriptor 2 (stderr) to file descriptor 1 (stdout) in TCL I think, different from shell.
https://core.tcl-lang.org/tips/doc/trunk/tip/202.md

Comment (yang-z-o) [reply tests/unit/tls.tcl:361]:
```
[ok]: TLS: Fail-fast on invalid certificates at startup (71 ms)
[ok]: TLS: Fail-fast on invalid certificates at runtime (7 ms)
```

**Comment by yang-z-o** [comment]
Hi @zuiderkwast,

I think I figured out the issue with `./runtest --tls` on mac OS now, and wanted to check whether this is a common issue or something we should document in the README.

macOS ships with a system `tclsh` that links against LibreSSL:
```
% tclsh
% package require tls
1.6.1
% puts [tls::version]
LibreSSL 3.3.6
```

Because tcl is present, `./runtest --tls` doesn’t fail early, but the server logs:
`SSL routines::unsupported protocol`

The server itself is correctly built against OpenSSL 3 because of this line in makefile:
https://github.com/valkey-io/valkey/blob/c1b4129eabca5f991ae227dd78241570c87dd245/src/Makefile#L178-L180
```
% otool -L ./src/valkey-server | grep ssl
/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
```

The problem is that the TLS client in tests is still using system LibreSSL, so we end up with a client (LibreSSL) ↔ server (OpenSSL 3) mismatch.
Therefore, we need to install a second `tclsh` under the same directory that makefile specified via: `brew install tcl-tk openssl@3`, so that we have `tclsh` under the specified directory `OPENSSL_PREFIX?=/opt/homebrew/opt/openssl`:
```
% /opt/homebrew/bin/tclsh
% package require tls
1.8.0
% puts [tls::version]
OpenSSL 3.6.0 1 Oct 2025
```

**Comment by yang-z-o** [comment]
Rebased onto the latest `unstable` to resolve conflicts.
Opened the PR for TLS https://github.com/valkey-io/valkey-doc/pull/402

**Comment by madolson** [comment]
@yang-z-o @zuiderkwast We talked about this PR while reviewing https://github.com/valkey-io/valkey/pull/2999, and it came up that this might also be considered a breaking change. We were aligned that it's the right long term behavior that we should reject, but we decided to revert this for 9.1 and move it to 10.0. We'll do this after the RC though.

**Comment by madolson** [comment]
@zuiderkwast @yang-z-o Just to ping folks. We decided to revert this from 9.1 since this felt like a breaking change, we then merged this into unstable thinking the next release was 10.0, but we decided to 9.2. Should we revert this just in 9.2 release branch again?

**Comment by zuiderkwast** [comment]
> We decided to revert this from 9.1 since this felt like a breaking change, we then merged this into unstable thinking the next release was 10.0, but we decided to 9.2. Should we revert this just in 9.2 release branch again?

Oh, I missed that and forgot we decided that. I saw it when going over the 9.2 board and saw it was ready. :/

Sure, we can revert it again then. (I don't think it's a problem to release it though. IMO, users relying on misconfiguration, such as empty files/directories, isn't something we need to worry about regarding semver. It's like if anyone is relying on a bug - that doesn't prevent us from fixing bugs.)
