### PR TITLE
Fix potential infinite loop in `clusterNodeGetPrimary`

### LINKED ISSUE #609: [BUG] Flaky cluster tests `11-manual-takeover.tcl` in 7.2
This happened in 7.2 branch. `11-manual-takeover.tcl` failed with `Error: The operation was canceled.`

https://github.com/valkey-io/valkey/actions/runs/9409039001/job/25920054481?pr=608#step:9:434

### PR DESCRIPTION
**Pull request by PingXie**
The original function could enter an infinite loop if there was a cycle in the replica chain. This change adds a check to break the loop if the node's replicaof eventually points back to itself. Additionally, a debugAssert has been added to ensure the replica/primary chain forms a tree structure and does not have any cycles.

Fix #609

### CODE REVIEW

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -3128,39 +3128,7 @@ int clusterProcessPacket(clusterLink *link) {
             clusterUpdateSlotsConfigWith(sender_primary, senderConfigEpoch, hdr->myslots);
 
         /* Explicitly check for a replication loop before attempting the replication
-         * chain folding logic.
```
Comment (enjoy-binbin) [inline src/cluster_legacy.c:3131]: the comment is outupdated so we remove it? (i did not bother to read it...)

**Review by enjoy-binbin — APPROVED** [review]

File: src/cluster_legacy.c (hunk 1 above)
Comment (PingXie) [reply src/cluster_legacy.c:3131]: Yes this particular circular replicaof chain is fixed

**Comment by apersson** [comment]
@PingXie , we are running Valkey 9.0.4, and we are still hitting an infinite loop in `clusterNodeGetMaster()`. However, in our case the `node` is not part of the cycle, but rather leads to it ( A -> (B <-> C)). Would you recommend adding even stronger cycle-detection?
